### ISSUE TITLE
Using string for transaction id instead of number

### ISSUE THREAD

**Issue by namchuai** [starkware-libs/starkex-js#15]
**Is your feature request related to a problem? Please describe.**
Transaction id will be very very big for a period of time. It should be send to starkEx as a string. Can cause overflow.

**Describe the solution you'd like**
Receive string for transaction id instead of number.

**Comment by dan-ziv** [comment]
Hey @namchuai 
Thanks for reporting.
We are aware of that - it will be fixed soon.

**Comment by dan-ziv** [comment]
Solves in https://github.com/starkware-libs/starkex-js/pull/20
